beacon_seq = comm.GoldSequence('FirstPolynomial',[10 3 0],...
              'FirstInitialConditions', 1,...
              'SecondPolynomial',[10 8 3 2 0],...
              'SecondInitialConditions', 1,...
              'Index', 0, 'Shift', 12, 'SamplesPerFrame', 1023);

tag_seq = comm.GoldSequence("FirstPolynomial", [10 3 0], "FirstInitialConditions", 1, ...
    "SecondPolynomial", [10 8 3 2 0], "SecondInitialConditions", 1, "Index", 1, ...
    "Shift", 9, "SamplesPerFrame", 1023);      
          
          
beacon_prn = step(beacon_seq);
tag_prn = step(tag_seq);

beacon_prn = 2*beacon_prn - 1;
tag_prn = 2*tag_prn - 1;
